import { chmod, open } from "node:fs/promises";
import { posix, win32 } from "node:path";

export const runtimeChoices = ["codex", "opencode", "antigravity"] as const;

export type RuntimeChoice = (typeof runtimeChoices)[number];
export type HostPlatform = "linux" | "macos" | "windows";

export type SetupAnswers = {
  ownerTelegramUserId: string;
  telegramBotToken: string;
  databaseUrl: string;
  runtimes: RuntimeChoice[];
};

export type WriteResult = {
  path: string;
  action: "created" | "skipped";
};

export type HostPaths = {
  dataDir: string;
  logDir: string;
  workspaceDir: string;
  artifactDir: string;
};

const runtimeLabels: Record<RuntimeChoice, string> = {
  codex: "Codex CLI",
  opencode: "OpenCode CLI",
  antigravity: "Antigravity CLI",
};

export function isRuntimeChoice(value: string): value is RuntimeChoice {
  return runtimeChoices.includes(value as RuntimeChoice);
}

export function runtimeLabel(runtime: RuntimeChoice) {
  return runtimeLabels[runtime];
}

export function detectHostPlatform(platform = process.platform): HostPlatform {
  if (platform === "linux") return "linux";
  if (platform === "darwin") return "macos";
  if (platform === "win32") return "windows";
  throw new Error(`unsupported host platform: ${platform}`);
}

function homeDir(env: Record<string, string | undefined>) {
  return env.HOME ?? env.USERPROFILE ?? ".";
}

export function defaultHostPaths(
  platform: HostPlatform = detectHostPlatform(),
  env: Record<string, string | undefined> = Bun.env,
): HostPaths {
  if (platform === "macos") {
    const home = homeDir(env);
    const dataDir = posix.join(
      home,
      "Library",
      "Application Support",
      "Param Agent",
    );
    return {
      dataDir,
      logDir: posix.join(home, "Library", "Logs", "Param Agent"),
      workspaceDir: posix.join(dataDir, "workspaces"),
      artifactDir: posix.join(dataDir, "artifacts"),
    };
  }

  if (platform === "windows") {
    const root = env.LOCALAPPDATA
      ? win32.join(env.LOCALAPPDATA, "Param Agent")
      : win32.join(homeDir(env), "AppData", "Local", "Param Agent");
    const dataDir = win32.join(root, "Data");
    return {
      dataDir,
      logDir: win32.join(root, "Logs"),
      workspaceDir: win32.join(dataDir, "workspaces"),
      artifactDir: win32.join(dataDir, "artifacts"),
    };
  }

  const dataRoot =
    env.XDG_DATA_HOME ?? posix.join(homeDir(env), ".local", "share");
  const stateRoot =
    env.XDG_STATE_HOME ?? posix.join(homeDir(env), ".local", "state");
  const dataDir = posix.join(dataRoot, "param-agent");
  return {
    dataDir,
    logDir: posix.join(stateRoot, "param-agent", "logs"),
    workspaceDir: posix.join(dataDir, "workspaces"),
    artifactDir: posix.join(dataDir, "artifacts"),
  };
}

export function pickDefaultRuntime(runtimes: RuntimeChoice[]) {
  if (runtimes.length === 0) {
    throw new Error("at least one runtime must be selected");
  }

  return runtimes.includes("codex") ? "codex" : runtimes[0];
}

export function buildEnvFile(answers: SetupAnswers) {
  return `# Generated by Param setup.
# Secrets and machine-specific values live here.

# Database
DATABASE_PROVIDER=local
DATABASE_PROVISIONING_MODE=local-postgres
DATABASE_URL=${serializeEnvValue(answers.databaseUrl)}

# Telegram
TELEGRAM_BOT_TOKEN=${serializeEnvValue(answers.telegramBotToken)}

# First trusted owner and default allowed DM user.
PARAM_OWNER_TELEGRAM_USER_ID=${serializeEnvValue(answers.ownerTelegramUserId)}

# Optional runtime overrides
CODEX_HOME=
OPENCODE_CONFIG_DIR=
ANTIGRAVITY_CONFIG_DIR=

# Optional public URL, required for webhooks / Mini Apps / OAuth callbacks
PARAM_PUBLIC_BASE_URL=

# Optional webhook secret, only required in webhook mode
TELEGRAM_WEBHOOK_SECRET=

# Optional admin/internal access
TAILSCALE_AUTH_KEY=

# App
PARAM_ENV=production
PARAM_LOG_LEVEL=info
`;
}

export function serializeEnvValue(value: string) {
  return JSON.stringify(value);
}

export function buildLocalConfigFile(answers: Pick<SetupAnswers, "runtimes">) {
  const enabled = new Set(answers.runtimes);
  const defaultRuntime = pickDefaultRuntime(answers.runtimes);
  const paths = defaultHostPaths();

  return `// Local Param config overrides.
//
// This file is ignored by git.
// Put per-instance non-secret settings here.
//
// Generated by Param setup.
//
// Do not put secrets here.
// Put bot tokens, database URLs, and API keys in .env.

import type { ParamConfigOverride } from "./src/config/schema";

export default {
  paths: {
    dataDir: ${JSON.stringify(paths.dataDir)},
    logDir: ${JSON.stringify(paths.logDir)},
    workspaceDir: ${JSON.stringify(paths.workspaceDir)},
    artifactDir: ${JSON.stringify(paths.artifactDir)},
  },
  actor: {
    defaultRuntime: "${defaultRuntime}",
  },
  runtimes: {
    codex: {
      enabled: ${enabled.has("codex")},
    },
    opencode: {
      enabled: ${enabled.has("opencode")},
    },
    antigravity: {
      enabled: ${enabled.has("antigravity")},
    },
  },
} satisfies ParamConfigOverride;
`;
}

export async function writeIfMissing(path: string, content: string) {
  if (await Bun.file(path).exists()) {
    return { path, action: "skipped" } satisfies WriteResult;
  }

  await Bun.write(path, content);
  return { path, action: "created" } satisfies WriteResult;
}

export async function writeSecretFileIfMissing(
  path: string,
  content: string,
  platform: HostPlatform = detectHostPlatform(),
) {
  let handle: Awaited<ReturnType<typeof open>> | undefined;

  try {
    handle = await open(path, "wx", 0o600);
  } catch (error) {
    if (isFileExistsError(error)) {
      return { path, action: "skipped" } satisfies WriteResult;
    }

    throw error;
  }

  try {
    await handle.writeFile(content);
  } finally {
    await handle.close();
  }

  if (platform !== "windows") {
    await chmod(path, 0o600);
  }

  return { path, action: "created" } satisfies WriteResult;
}

function isFileExistsError(error: unknown) {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    error.code === "EEXIST"
  );
}
