import { randomBytes } from "node:crypto";
import { chmod, open } from "node:fs/promises";
import { posix, win32 } from "node:path";

export const runtimeChoices = ["codex", "opencode", "antigravity"] as const;

export type RuntimeChoice = (typeof runtimeChoices)[number];
export type HostPlatform = "linux" | "macos" | "windows";

export type SetupAnswers = {
  ownerTelegramUserId: string;
  telegramBotToken: string;
  databaseUrl: string;
  /** OpenAI API key for the default brain; "" when using Codex login / none. */
  openaiApiKey: string;
  /**
   * Optional Tailscale auth key for NON-interactive tailnet join (CI/automation).
   * Normally left unset: the installer connects via a browser login link
   * (`tailscale up`, codex-style), so there is nothing to paste here.
   */
  tailscaleAuthKey?: string;
  runtimes: RuntimeChoice[];
};

export type WriteResult = {
  path: string;
  action: "created" | "skipped";
};

export type HostPaths = {
  dataDir: string;
  logDir: string;
  workspaceDir: string;
  artifactDir: string;
};

const runtimeLabels: Record<RuntimeChoice, string> = {
  codex: "Codex CLI",
  opencode: "OpenCode CLI",
  antigravity: "Antigravity CLI",
};

export function isRuntimeChoice(value: string): value is RuntimeChoice {
  return runtimeChoices.includes(value as RuntimeChoice);
}

export function runtimeLabel(runtime: RuntimeChoice) {
  return runtimeLabels[runtime];
}

export function detectHostPlatform(platform = process.platform): HostPlatform {
  if (platform === "linux") return "linux";
  if (platform === "darwin") return "macos";
  if (platform === "win32") return "windows";
  throw new Error(`unsupported host platform: ${platform}`);
}

function homeDir(env: Record<string, string | undefined>) {
  return env.HOME ?? env.USERPROFILE ?? ".";
}

export function defaultHostPaths(
  platform: HostPlatform = detectHostPlatform(),
  env: Record<string, string | undefined> = Bun.env,
): HostPaths {
  if (platform === "macos") {
    const home = homeDir(env);
    const dataDir = posix.join(
      home,
      "Library",
      "Application Support",
      "Param Agent",
    );
    return {
      dataDir,
      logDir: posix.join(home, "Library", "Logs", "Param Agent"),
      workspaceDir: posix.join(dataDir, "workspaces"),
      artifactDir: posix.join(dataDir, "artifacts"),
    };
  }

  if (platform === "windows") {
    const root = env.LOCALAPPDATA
      ? win32.join(env.LOCALAPPDATA, "Param Agent")
      : win32.join(homeDir(env), "AppData", "Local", "Param Agent");
    const dataDir = win32.join(root, "Data");
    return {
      dataDir,
      logDir: win32.join(root, "Logs"),
      workspaceDir: win32.join(dataDir, "workspaces"),
      artifactDir: win32.join(dataDir, "artifacts"),
    };
  }

  const dataRoot =
    env.XDG_DATA_HOME ?? posix.join(homeDir(env), ".local", "share");
  const stateRoot =
    env.XDG_STATE_HOME ?? posix.join(homeDir(env), ".local", "state");
  const dataDir = posix.join(dataRoot, "param-agent");
  return {
    dataDir,
    logDir: posix.join(stateRoot, "param-agent", "logs"),
    workspaceDir: posix.join(dataDir, "workspaces"),
    artifactDir: posix.join(dataDir, "artifacts"),
  };
}

export function pickDefaultRuntime(runtimes: RuntimeChoice[]) {
  if (runtimes.length === 0) {
    throw new Error("at least one runtime must be selected");
  }

  return runtimes.includes("codex") ? "codex" : runtimes[0];
}

export function buildEnvFile(answers: SetupAnswers) {
  return `# Generated by Param setup.
# Secrets and machine-specific values live here.

# Database
DATABASE_PROVIDER=local
DATABASE_PROVISIONING_MODE=local-postgres
DATABASE_SSL=false
DATABASE_URL=${serializeEnvValue(answers.databaseUrl)}

# Telegram
TELEGRAM_BOT_TOKEN=${serializeEnvValue(answers.telegramBotToken)}

# First trusted owner and default allowed DM user.
PARAM_OWNER_TELEGRAM_USER_ID=${serializeEnvValue(answers.ownerTelegramUserId)}

# Session Actor brain.
# PARAM_ACTOR: auto (default) | openai | codex | mock.
#   auto  -> OpenAI API brain when OPENAI_API_KEY is set, else the codex CLI.
#   mock  -> deterministic actor (canned replies); only for testing.
# In production a missing real brain refuses to start (never silently mocks).
PARAM_ACTOR=
OPENAI_API_KEY=${serializeEnvValue(answers.openaiApiKey)}
PARAM_OPENAI_MODEL=

# Optional runtime overrides
CODEX_HOME=
OPENCODE_CONFIG_DIR=
ANTIGRAVITY_CONFIG_DIR=

# Optional public URL, required for webhooks / Mini Apps / OAuth callbacks
PARAM_PUBLIC_BASE_URL=

# Optional webhook secret, only required in webhook mode
TELEGRAM_WEBHOOK_SECRET=

# Private access. Tailscale is installed by default and connects via a browser
# login link during install (like 'codex login') — reach the box over the
# tailnet; app endpoints stay bound to loopback. Leave this blank for the login
# flow. Only set an auth key for NON-interactive joins (CI/automation), or run
# 'sudo tailscale up' anytime to (re)connect.
TAILSCALE_AUTH_KEY=${serializeEnvValue(answers.tailscaleAuthKey ?? "")}

# Optional bearer token to protect /operator/* and /health/db when the app is
# bound to a public/Tailscale interface (PARAM_BIND_HOST). Loopback by default.
PARAM_OPERATOR_TOKEN=

# App
PARAM_ENV=production
PARAM_LOG_LEVEL=info
`;
}

export function serializeEnvValue(value: string) {
  // Bun's dotenv expands $VAR / ${VAR} inside .env values even when quoted, so a
  // secret containing `$` (common in strong passwords / DB URLs) would be
  // mangled — e.g. `p$word` -> `p`. We wrap in double quotes and escape `$`
  // -> `\$`, which Bun reads back as a literal `$` (and it performs no command
  // substitution / backtick expansion, so `$(...)`/backticks are inert once the
  // leading `$` is escaped).
  //
  // One quirk: Bun keeps the backslash of a `\$` that sits at the very end of
  // the value (right before the closing quote) — `"abc\$"` reads back as
  // `abc\$`. A trailing `$` needs no escaping there (nothing follows it to
  // expand), so we un-escape that single trailing `\$` back to `$`.
  //
  // Bun's double-quote parser is otherwise NOT JSON-compatible: it un-escapes
  // only \n / \r / \$ and leaves \" and \\ (and \t etc.) literal. So a value
  // with a raw `"`, `\`, or control char would NOT read back byte-for-byte.
  // That is fine for the numeric owner id and the regex-restricted bot token,
  // which cannot contain those. DATABASE_URL is not guaranteed percent-encoded,
  // so callers gate it with `envValueRoundTrips` and reject un-round-trippable
  // input up front (see scripts/setup.ts) rather than let it mangle silently.
  return JSON.stringify(value)
    .replace(/\$/g, "\\$")
    .replace(/\\\$"$/, () => '$"');
}

// True iff `value` survives serializeEnvValue -> Bun dotenv byte-for-byte.
// Bun un-escapes only \n / \r / \$ in a double-quoted value, so a raw `"`,
// a `\`, an ASCII control char, or a lone surrogate (JSON.stringify emits a
// \uXXXX escape that Bun does not decode) does NOT round-trip. (\n / \r
// technically would, but a single-line prompt can't produce them, so we reject
// all control chars for safety.)
export function envValueRoundTrips(value: string) {
  for (const ch of value) {
    const code = ch.charCodeAt(0);
    if (ch === '"' || ch === "\\" || code < 0x20) return false;
    // Lone surrogate: `for...of` yields it as a length-1 unit (a valid pair is
    // length 2). JSON.stringify escapes it as \uXXXX, which Bun won't decode.
    if (ch.length === 1 && code >= 0xd800 && code <= 0xdfff) return false;
  }
  return true;
}

// A strong random password for the auto-provisioned local database. base64url
// (A-Za-z0-9-_) is URL-safe, so it needs no percent-encoding and round-trips
// through .env cleanly; 24 bytes ~= 192 bits of entropy.
export function generateDbPassword() {
  return randomBytes(24).toString("base64url");
}

// Assemble a Postgres URL, percent-encoding the userinfo so any password
// character is stored safely (the caller never has to encode by hand).
export function buildDatabaseUrl(
  password: string,
  opts: {
    user?: string;
    host?: string;
    port?: string | number;
    database?: string;
  } = {},
) {
  const user = opts.user ?? "param";
  const host = opts.host ?? "127.0.0.1";
  const port = opts.port ?? 5432;
  const database = opts.database ?? "param";
  return `postgresql://${encodeURIComponent(user)}:${encodeURIComponent(password)}@${host}:${port}/${database}`;
}

export function buildLocalConfigFile(answers: Pick<SetupAnswers, "runtimes">) {
  const enabled = new Set(answers.runtimes);
  const defaultRuntime = pickDefaultRuntime(answers.runtimes);
  const paths = defaultHostPaths();

  return `// Local Param config overrides.
//
// This file is ignored by git.
// Put per-instance non-secret settings here.
//
// Generated by Param setup.
//
// Do not put secrets here.
// Put bot tokens, database URLs, and API keys in .env.

import type { ParamConfigOverride } from "./src/config/schema";

export default {
  paths: {
    dataDir: ${JSON.stringify(paths.dataDir)},
    logDir: ${JSON.stringify(paths.logDir)},
    workspaceDir: ${JSON.stringify(paths.workspaceDir)},
    artifactDir: ${JSON.stringify(paths.artifactDir)},
  },
  actor: {
    defaultRuntime: "${defaultRuntime}",
  },
  runtimes: {
    codex: {
      enabled: ${enabled.has("codex")},
    },
    opencode: {
      enabled: ${enabled.has("opencode")},
    },
    antigravity: {
      enabled: ${enabled.has("antigravity")},
    },
  },
} satisfies ParamConfigOverride;
`;
}

export async function writeIfMissing(path: string, content: string) {
  if (await Bun.file(path).exists()) {
    return { path, action: "skipped" } satisfies WriteResult;
  }

  await Bun.write(path, content);
  return { path, action: "created" } satisfies WriteResult;
}

export async function writeSecretFileIfMissing(
  path: string,
  content: string,
  platform: HostPlatform = detectHostPlatform(),
) {
  let handle: Awaited<ReturnType<typeof open>> | undefined;

  try {
    handle = await open(path, "wx", 0o600);
  } catch (error) {
    if (isFileExistsError(error)) {
      return { path, action: "skipped" } satisfies WriteResult;
    }

    throw error;
  }

  try {
    await handle.writeFile(content);
  } finally {
    await handle.close();
  }

  if (platform !== "windows") {
    await chmod(path, 0o600);
  }

  return { path, action: "created" } satisfies WriteResult;
}

function isFileExistsError(error: unknown) {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    error.code === "EEXIST"
  );
}
